# Generated by Django 2.2.3 on 2019-08-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevcheckdata',
            name='prev_detail_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
