# Generated by Django 2.2.3 on 2019-08-07 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190807_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prevcheckdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='prevcheckdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
