# Generated by Django 2.2.3 on 2019-08-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190807_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prev_brandCheck',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
