# Generated by Django 2.2.3 on 2019-08-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_uploadfilemodel_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='saletype',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
