# Generated by Django 2.2.3 on 2019-08-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_uploadfilemodel_saletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='bidprice',
            field=models.IntegerField(null=True),
        ),
    ]
