# Generated by Django 2.2.3 on 2019-08-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_uploadfilemodel_bidprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='biduser',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
